name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

# 允许 GITHUB_TOKEN 进行部署
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages # 构建好的网页将放在这个分支